<table class="table">
    <tr>
        <th>#</th>
        <th>nome</th>
        <th>email</th>
        <th>telefone</th>
        <th>horas por dia</th>
    </tr>
    <tr>
        <td><?php echo $this->escapeHtml($usuario->id);?></td>
        <td><?php echo $this->escapeHtml($usuario->nome);?></td>
        <td><?php echo $this->escapeHtml($usuario->email);?></td>
        <td><?php echo $this->escapeHtml($usuario->telefone);?></td>
        <td><?php echo $this->escapeHtml($usuario->horas_dia);?></td>
    </tr>
</table>
