<?php
$title = 'Remover album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
 
<p>Tem certeza que deseja remover esse album?
    '<?php echo $this->escapeHtml($album->getTitle()); ?>' por
    '<?php echo $this->escapeHtml($album->getArtist()); ?>'?
</p>
<?php
$url = $this->url('album', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $album->getId(); ?>" />
    <input class="btn btn-danger" type="submit" name="del" value="Yes" />
    <input class="btn btn-success" type="submit" name="del" value="No" />
</div>
</form>