<?php
$title = 'Editar album';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('title')); ?>
		<?php echo $this->formInput($form->get('title')); ?>
		<?php echo $this->formElementErrors($form->get('title')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('artist')); ?>
		<?php echo $this->formInput($form->get('artist')); ?>
		<?php echo $this->formElementErrors($form->get('artist')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formSubmit($form->get('submit')); ?>
	</div>
<?php echo $this->form()->closeTag(); ?>