<?php
$title = 'Editar album';
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'edit', 'id' => $this->id)));
$form->prepare();
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formHidden($form->get('id')); ?>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('title')); ?>
		<?php echo $this->formInput($form->get('title')); ?>
		<?php echo $this->formElementErrors($form->get('title')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formLabel($form->get('artist')); ?>
		<?php echo $this->formInput($form->get('artist')); ?>
		<?php echo $this->formElementErrors($form->get('artist')); ?>
	</div>
	<div class="form-group">
		<?php echo $this->formSubmit($form->get('submit')); ?>
	</div>
<?php echo $this->form()->closeTag(); ?>

<?php if(count($tracks) > 0): ?>
	<h2>Músicas</h2>
	<table class="table">
	<tr>
	    <th>Título</th>
	    <th>&nbsp;</th>
	</tr>
	<?php foreach($tracks as $track): ?>
	<tr>
	    <td><?php echo $this->escapeHtml($track->getTrackTitle());?></td>
	    <td>
	        <a class="btn btn-xs btn-warning" href="<?php echo $this->url('album',array('action'=>'edit-track', 'id' => $track->getTrackId()));?>"><span class="glyphicon glyphicon-edit"></a>
	        <a class="btn btn-xs btn-danger" href="<?php echo $this->url('album', array('action'=>'delete-track', 'id' => $track->getTrackId()));?>"><span class="glyphicon glyphicon-floppy-remove"></a>
	    </td>
	</tr>
	<?php endforeach; ?>
	</table>
<?php endif;?>